<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-13 10:13

import django.db.models.deletion
=======
# Generated by Django 5.2.7 on 2025-10-21 14:35

>>>>>>> a978398 (LAB-4 ARPI EN PROCESO)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('level', models.IntegerField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='trainer_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('PS', 'Psíquico'), ('E', 'Eléctrico'), ('A', 'Agua'), ('H', 'Hielo'), ('T', 'Tierra'), ('V', 'Veneno'), ('F', 'Fuego'), ('P', 'Planta'), ('L', 'Lagartija'), ('N', 'Normal')], max_length=30)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pokemon_pictures/')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer')),
=======
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=40)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
>>>>>>> a978398 (LAB-4 ARPI EN PROCESO)
            ],
        ),
    ]
