# Generated by Django 5.2.8 on 2025-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('PS', 'Psíquico'), ('A', 'Agua'), ('V', 'Veneno'), ('H', 'Hielo'), ('F', 'Fuego'), ('L', 'Lagartija'), ('N', 'Normal')], max_length=30),
        ),
    ]
