# Generated by Django 5.2.8 on 2025-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('N', 'Normal'), ('PS', 'Psíquico'), ('H', 'Hielo'), ('P', 'Planta'), ('E', 'Eléctrico'), ('L', 'Lagartija'), ('V', 'Veneno'), ('T', 'Tierra')], max_length=30),
        ),
    ]
