# Generated by Django 5.2.7 on 2025-10-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='type',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='height',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='weight',
            new_name='last_name',
        ),
    ]
