# Generated by Django 5.2.7 on 2025-10-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_rename_type_trainer_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='birthday',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='age',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='last_name',
            new_name='weight',
        ),
    ]
