# Generated by Django 5.2.7 on 2025-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('L', 'Lagartija'), ('A', 'Agua'), ('PS', 'Psíquico'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('P', 'Planta'), ('N', 'Normal'), ('V', 'Veneno'), ('H', 'Hielo')], max_length=30),
        ),
    ]
