# Generated by Django 5.2.8 on 2026-01-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Eléctrico'), ('V', 'Veneno'), ('P', 'Planta'), ('N', 'Normal'), ('L', 'Lagartija'), ('T', 'Tierra'), ('PS', 'Psíquico'), ('H', 'Hielo'), ('A', 'Agua')], max_length=30),
        ),
    ]
