# Generated by Django 5.2.8 on 2026-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('V', 'Veneno'), ('H', 'Hielo'), ('A', 'Agua'), ('E', 'Eléctrico'), ('P', 'Planta'), ('PS', 'Psíquico'), ('T', 'Tierra'), ('L', 'Lagartija'), ('F', 'Fuego'), ('N', 'Normal')], max_length=30),
        ),
    ]
