# Generated by Django 5.2.8 on 2026-01-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('PS', 'Psíquico'), ('V', 'Veneno'), ('N', 'Normal'), ('P', 'Planta'), ('F', 'Fuego'), ('E', 'Eléctrico'), ('A', 'Agua'), ('H', 'Hielo'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
